<?php

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogProductOptionComposite\Block\Product\View\Bundle;

/** @var Bundle $block */
?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogProductCompositeBundle": {
                "index": <?= /* @noEscape */ $block->getIndex(); ?>
            }
        }
    }
</script>
