<?php /** @noinspection PhpUnhandledExceptionInspection */

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogProductOptionComposite\Block\Quote\Item\Bundle;
use Magento\Framework\Escaper;
use Magento\Framework\View\TemplateEngine\Php;

/** @var Php $this */
/** @var Escaper $escaper */
/** @var Bundle $block */

$product = $block->getProduct();
$subline = $product->getData('quote_item_bundle_subline');
$description = $product->getData('quote_item_bundle_description');
?>

<?php if ($subline): ?>
    <h2><?= $subline; ?></h2>
<?php endif; ?>

<?php if ($description): ?>
    <div class="description"><?= $description; ?></div>
<?php endif; ?>
