<?php /** @noinspection PhpUnhandledExceptionInspection */

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogProductOptionComposite\Block\Quote\Item\Bundle\Products\Selection\Options;
use Magento\Framework\Escaper;
use Magento\Framework\View\TemplateEngine\Php;

/** @var Php $this */
/** @var Escaper $escaper */
/** @var Options $block */

$bundleOption = $block->getBundleOption();
$product = $block->getProduct();
$options = $block->getOptions();
?>

<?php if ($options): ?>
    <script type="text/x-magento-init">
        {
            "#quote-item-bundle-selection-<?= /* @noEscape */ $bundleOption->getId(); ?>": {
                "priceOptions": {
                    "optionConfig": <?= /* @noEscape */ $block->getJsonConfig(); ?>,
                    "controlContainer": ".field",
                    "priceHolderSelector": "[data-price-box-id='quote-item-bundle-selection-id-<?= $bundleOption->getId(); ?>'][data-role=priceBox]"
                }
            }
        }
    </script>
    <div class="product-options-wrapper quote-item-bundle-selection-options-wrapper" id="quote-item-bundle-selection-options-wrapper-<?= /* @noEscape */ $bundleOption->getId(); ?>">
        <div class="fieldset">
            <?php foreach ($options as $option): ?>
                <?= $block->getBundleOptionHtml(
                        $bundleOption,
                        $product,
                        $option); ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="product-options-price">
        <div class="price-box"
             data-role="priceBox"
             data-price-box-id="quote-item-bundle-selection-id-<?= $bundleOption->getId(); ?>">
            <?= /* @noEscape */ $block->renderAmount(
                [
                    'price_id'          => 'quote-item-bundle-selection-price-' . $bundleOption->getId(),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema'            => 'item_view'
                ]
            ); ?>
        </div>
        <script type="text/x-magento-init">
            {
                "[data-role=priceBox][data-price-box-id=quote-item-bundle-selection-id-<?= /* @noEscape */ $bundleOption->getId(); ?>]": {
                    "priceBox": {
                        "priceConfig": {
                            "priceFormat": <?= /* @noEscape */ $block->getPriceFormatJson(); ?>,
                            "prices": <?= /* @noEscape */ $block->getPricesJson(); ?>
                        }
                    }
                }
            }
        </script>
    </div>
<?php endif; ?>
