<?php /** @noinspection PhpUnhandledExceptionInspection */

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogProductOptionComposite\Block\Quote\Item\Bundle;
use Magento\Framework\Escaper;
use Magento\Framework\View\TemplateEngine\Php;

/** @var Php $this */
/** @var Escaper $escaper */
/** @var Bundle $block */
?>

<div class="cart-container">
    <form action="<?= $escaper->escapeUrl($block->getUrl('catalog_product_option_composite/quote_item/update')); ?>"
          method="post"
          class="form form-cart">
        <?= $block->getBlockHtml('formkey'); ?>
        <input type="hidden" name="item_id" value="<?= /* @noEscape */ $block->getItem()->getId(); ?>" />
        <div class="products wrapper grid products-grid">
            <?= $block->getProductsHtml(); ?>
        </div>
        <div class="cart main actions">
            <button type="submit"
                    name="update_cart_action"
                    value="update_qty"
                    title="<?= $escaper->escapeHtml(__('Update Shopping Cart')); ?>"
                    class="action primary update">
                <span><?= $escaper->escapeHtml(__('Update Shopping Cart')); ?></span>
            </button>
        </div>
    </form>
</div>
