<?php /** @noinspection PhpUnhandledExceptionInspection */

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogProductOptionComposite\Block\Quote\Item\Bundle;
use Magento\Framework\Escaper;
use Magento\Framework\View\TemplateEngine\Php;

/** @var Php $this */
/** @var Escaper $escaper */
/** @var Bundle $block */
?>

<div class="header">
    <?= $block->getChildHtml('quote.item.bundle.header'); ?>
</div>

<div class="cart-container">
    <form action="<?= $escaper->escapeUrl($block->getUrl('catalog_product_option_composite/quote_item/update')); ?>"
          method="post"
          class="form form-cart">
        <?= $block->getBlockHtml('formkey'); ?>
        <input type="hidden" name="item_id" value="<?= /* @noEscape */ $block->getItem()->getId(); ?>" />
        <?= $block->getChildHtml('quote.item.bundle.products.before'); ?>
        <div class="products wrapper grid products-grid">
            <?= $block->getProductsHtml(); ?>
        </div>
        <?= $block->getChildHtml('quote.item.bundle.products.after'); ?>
        <div class="cart main actions">
            <?= $block->getChildHtml('quote.item.bundle.actions'); ?>
        </div>
    </form>
</div>
